Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,13 @@ jobs:
         pdflatex ./Resume/Resume.tex
         pdflatex ./Resume/Resume.tex  # Run twice to resolve references
 
+    - name: Check if PDF was created
+      run: |
+        if [ ! -f ./Resume/Resume.pdf ]; then
+          echo "Resume.pdf not found!"
+          exit 1
+        fi
+
     - name: Read current version
       id: read_version
       run: |
@@ -58,7 +65,7 @@ jobs:
       uses: softprops/action-gh-release@v1
       with:
         tag_name: v${{ steps.increment_version.outputs.new_version }}  # Tag based on new version
-        release_name: "Resume v${{ steps.increment_version.outputs.new_version }}"
+        name: "Resume v${{ steps.increment_version.outputs.new_version }}"  # Use name instead of release_name
         files: ./Resume/Resume.pdf
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
