Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,7 +13,22 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Set up TeX Live
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y texlive-full
 
+    - name: Compile LaTeX to PDF
+      run: |
+        pdflatex -output-directory=./Resume ./Resume/Resume.tex
+        pdflatex -output-directory=./Resume ./Resume/Resume.tex  # Run twice for references
+
+    - name: Check if PDF was created
+      run: |
+        if [ ! -f ./Resume.pdf ]; then
+          echo "Resume.pdf not found!"
+          exit 1
+        fi
 
     - name: Read current version
       id: read_version
@@ -48,16 +63,14 @@ jobs:
     - name: List files for debug
       run: ls -R  # Lists all files and directories recursively for troubleshooting
 
-    - name: Install GitHub CLI
-      run: |
-        sudo apt-get install -y gh
 
-    - name: Create Release with GitHub CLI
+    - uses: jakob-lilliemarck/action-ez-release@v1
+      with:
+        tag_name: _test
+        release_artifacts: Resume.pdf
       env:
-        GITHUB_TOKEN: ${{ github.token }}
-      run: |
-        gh release create "v${{ env.new_version }}" ./Resume/Resume.pdf --title "Resume v${{ env.new_version }}" --notes "Automated release of Resume version ${{ env.new_version }}" --draft
-
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+ 
     - name: Update README.md
       run: |
         version="v${{ env.new_version }}"
